git:
  submodules: false

sudo: required
dist: trusty

language: c++

#compiler:
#  - gcc
#  - clang

matrix:
  include:
    - os: linux
      compiler: gcc-7
      env:
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libglu1-mesa-dev
            - xorg-dev
    - os: linux
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libglu1-mesa-dev
            - xorg-dev
#    - os: osx
#      osx_image: xcode9.4
#    - os: osx
#      osx_image: xcode9
#    - os: osx
#      osx_image: xcode8

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
  #- cmake --build .
  - make
