git:
  submodules: false

language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode8

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
