language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode8

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
